// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: proto/sql/nullfloat.proto

package sql

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type NullFloat64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val   float64 `protobuf:"fixed64,1,opt,name=val,proto3" json:"val,omitempty"`
	Valid bool    `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *NullFloat64) Reset() {
	*x = NullFloat64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sql_nullfloat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullFloat64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullFloat64) ProtoMessage() {}

func (x *NullFloat64) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sql_nullfloat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullFloat64.ProtoReflect.Descriptor instead.
func (*NullFloat64) Descriptor() ([]byte, []int) {
	return file_proto_sql_nullfloat_proto_rawDescGZIP(), []int{0}
}

func (x *NullFloat64) GetVal() float64 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *NullFloat64) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type NullFloat32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val   float32 `protobuf:"fixed32,1,opt,name=val,proto3" json:"val,omitempty"`
	Valid bool    `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
}

func (x *NullFloat32) Reset() {
	*x = NullFloat32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_sql_nullfloat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullFloat32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullFloat32) ProtoMessage() {}

func (x *NullFloat32) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sql_nullfloat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullFloat32.ProtoReflect.Descriptor instead.
func (*NullFloat32) Descriptor() ([]byte, []int) {
	return file_proto_sql_nullfloat_proto_rawDescGZIP(), []int{1}
}

func (x *NullFloat32) GetVal() float32 {
	if x != nil {
		return x.Val
	}
	return 0
}

func (x *NullFloat32) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_proto_sql_nullfloat_proto protoreflect.FileDescriptor

var file_proto_sql_nullfloat_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x71, 0x6c, 0x2f, 0x6e, 0x75, 0x6c, 0x6c,
	0x66, 0x6c, 0x6f, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x75, 0x74, 0x68,
	0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x73, 0x71, 0x6c, 0x22,
	0x35, 0x0a, 0x0b, 0x4e, 0x75, 0x6c, 0x6c, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x12, 0x10,
	0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x76, 0x61, 0x6c,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x22, 0x35, 0x0a, 0x0b, 0x4e, 0x75, 0x6c, 0x6c, 0x46, 0x6c,
	0x6f, 0x61, 0x74, 0x33, 0x32, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x03, 0x76, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x42, 0x2f, 0x5a,
	0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x75, 0x74, 0x68, 0x6e,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2d, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x73, 0x71, 0x6c, 0x3b, 0x73, 0x71, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_sql_nullfloat_proto_rawDescOnce sync.Once
	file_proto_sql_nullfloat_proto_rawDescData = file_proto_sql_nullfloat_proto_rawDesc
)

func file_proto_sql_nullfloat_proto_rawDescGZIP() []byte {
	file_proto_sql_nullfloat_proto_rawDescOnce.Do(func() {
		file_proto_sql_nullfloat_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_sql_nullfloat_proto_rawDescData)
	})
	return file_proto_sql_nullfloat_proto_rawDescData
}

var file_proto_sql_nullfloat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sql_nullfloat_proto_goTypes = []interface{}{
	(*NullFloat64)(nil), // 0: uthng.protobuf.sql.NullFloat64
	(*NullFloat32)(nil), // 1: uthng.protobuf.sql.NullFloat32
}
var file_proto_sql_nullfloat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sql_nullfloat_proto_init() }
func file_proto_sql_nullfloat_proto_init() {
	if File_proto_sql_nullfloat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_sql_nullfloat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullFloat64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_sql_nullfloat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullFloat32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_sql_nullfloat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sql_nullfloat_proto_goTypes,
		DependencyIndexes: file_proto_sql_nullfloat_proto_depIdxs,
		MessageInfos:      file_proto_sql_nullfloat_proto_msgTypes,
	}.Build()
	File_proto_sql_nullfloat_proto = out.File
	file_proto_sql_nullfloat_proto_rawDesc = nil
	file_proto_sql_nullfloat_proto_goTypes = nil
	file_proto_sql_nullfloat_proto_depIdxs = nil
}
